### ISSUE TITLE
Session Error

### ISSUE THREAD

**Issue by cursorius-cursor** [futursolo/FutureFinity#10]
Setting: OS-X, Python 3.5, fresh virtualenv, pip install FutureFinity (0.1.1)

Starting with the "HelloWorld" example nothing happens!
Adding app.settings["debug"] = True is throwing an error:

lib/python3.5/site-packages/futurefinity/interface/session.py", line 52, in write_session
    "No Session Interface Can be automatically Selected.")
NotImplementedError: No Session Interface Can be automatically Selected.

Reproduced on Debian Sid:
500: Internal Server Error
    
Traceback (most recent call last):
    
  File "/Envs/futurefinity-test/lib/python3.5/site-packages/futurefinity/web.py", line 584, in handle    body = await getattr(self, self.method.lower())(*args, **kwargs)
    
  File "test.py", line 18, in get    round_num = int(self.get_cookie("rofl-round", default=450))
    
  File "/Envs/futurefinity-test/lib/python3.5/site-packages/futurefinity/web.py", line 174, in get_cookie    return cookie.value
    
AttributeError: 'int' object has no attribute 'value'

**Comment by futursolo** [comment]
I found this is an Error caused by SessionInterfaceModel, I will fix this soon. 

You can prevent this issue temporarily by installing `aioredis` ,which is a Asynchronous Redis Library for asyncio. 

You don't have to install the whole redis database, just install the aioredis library from PyPI.

**Comment by futursolo** [comment]
For the second bug produced on debian, I will fix it soon, since they are two different bugs.
